# Generated by Django 5.0.2 on 2024-03-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='location',
        ),
    ]
